### ISSUE TITLE
missing file main.py

### ISSUE THREAD

**Issue by AmauryVanEspen** [hackersandslackers/flask-session-tutorial#2]
Good evening
it seems there is no file main.py to execute
Could you tell me more about executing this python web app ?
Thank you
Amaury

**Comment by toddbirchard** [comment]
Hi @AmauryVanEspen, **wsgi.py** should serve the same purpose here. Alternatively, running `flask run` in the directory will invoke this on your behalf, thanks to the presence of **start.sh**.
